name: jupyterlab-lsp

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtime dependencies
  - python >=3.6,<3.9.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - jupyter_server >=1.1.2
  - retrolab >=0.2.0,<0.3
  - jupyterlab-lsp
  - pip
  # for R language server and kernel
  - r
  - r-irkernel
  - r-languageserver
  # using R from Python
  - rpy2
